SELECT
    A.ID,
    A.GENOTYPE,
    B.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA AS A
JOIN
    ECOLI_DATA AS B ON B.ID = A.PARENT_ID
WHERE
    (A.GENOTYPE & B.GENOTYPE) = B.GENOTYPE
ORDER BY
    A.ID;